apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: m8jqqf9xh-go
  janus-idp.io/tekton: m8jqqf9xh-go
  backstage.io/kubernetes-id: m8jqqf9xh-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: m8jqqf9xh-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
