apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: m8jqqf9xh-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: m8jqqf9xh-go 
  name: m8jqqf9xh-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: m8jqqf9xh-go 
